services:
  app:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PORT: 80
      SECRET: ${JWT_SECRET}
      MONGO_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@db:27017
      MONGO_DB: pops-ticketing

  db:
    image: mongo:4
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongo-data:
  mongo-config:
